apiVersion: apps/v1
kind: Deployment
metadata:
  name: better-app
  labels:
    app: better
spec:
  replicas: 2
  selector:
    matchLabels:
      app: better
  template:
    metadata:
      labels:
        app: better
    spec:
      containers:
      - name: better-container
        image: your-registry/myapp:latest   # Replace with your image repo/tag
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
        - name: NODE_ENV
          value: "production"
