apiVersion: apps/v1
kind: Deployment
metadata:
  name: better-app
  labels:
    app: better
spec:
  replicas: 2
  selector:
    matchLabels:
      app: better
  template:
    metadata:
      labels:
        app: better
    spec:
      containers:
        - name: better-container
          image: navathej408/better-app:latest   # Use tag explicitly
          ports:
            - containerPort: 8001
