---
apiVersion: v1
kind: Service
metadata:
  name: better-service
spec:
  selector:
    app: better
  ports:
    - protocol: TCP
      port: 80           # Service port (external)
      targetPort: 3000   # Container port (internal)
  type: LoadBalancer     # For AWS ELB
