---
apiVersion: v1
kind: Service
metadata:
  name: better-service
spec:
  selector:
    app: better
  ports:
    - protocol: TCP
      port: 80           
      targetPort: 3000   
  type: LoadBalancer     # For AWS ELB
