apiVersion: v1
kind: Service
metadata:
  name: better-service
spec:
  selector:
    app: better
  ports:
    - protocol: TCP
      port: 80           # The port exposed by the Service
      targetPort: 3000   # The port your container listens on
  type: LoadBalancer    # Use NodePort if you don’t have a cloud LB
